/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 49;
=======
const int buildversion = 100;
>>>>>>> Carlo
const char buildconfig[] = "SHELL_PROJECT";
