/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 16;
=======
const int buildversion = 17;
>>>>>>> Carlo
const char buildconfig[] = "SHELL_PROJECT";
