/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 8;
=======
const int buildversion = 18;
>>>>>>> ce009212d71e5836efb699545753a6c7e06cfa17
const char buildconfig[] = "SHELL_PROJECT";
